#include "switchdrive/core.hpp"

#include <chrono>
#include <random>
#include <sstream>

namespace fs = std::filesystem;
namespace switchdrive {

std::string sanitizeFileName(const std::string& name) {
    std::string out;
    for (unsigned char c : name) {
        if (std::isalnum(c) || c == '.' || c == '_' || c == '-') out += static_cast<char>(c);
        else if (c == ' ') out += '_';
    }
    if (out.empty()) out = "download";
    if (out.size() > 120) out.resize(120);
    return out;
}
std::string extensionOf(const std::string& name) {
    const auto pos = name.find_last_of('.');
    if (pos == std::string::npos) return {};
    std::string ext = name.substr(pos);
    std::transform(ext.begin(), ext.end(), ext.begin(), [](unsigned char c){ return std::tolower(c); });
    return ext;
}
bool isNro(const std::string& name) { return extensionOf(name) == ".nro"; }
bool isNsp(const std::string& name) { return extensionOf(name) == ".nsp"; }
std::string makeId() {
    static std::mt19937_64 engine{static_cast<uint64_t>(std::chrono::high_resolution_clock::now().time_since_epoch().count())};
    std::ostringstream output; output << std::hex << engine() << engine(); return output.str();
}
bool fileExists(const std::string& path) { return fs::exists(fs::path(path)); }
uint64_t fileSize(const std::string& path) { std::error_code ec; return fs::file_size(fs::path(path), ec); }

// State is deliberately serialized by a single store. JSON escaping here covers
// data generated by Drive names and avoids treating input as a pathname.
static std::string escape(const std::string& value) {
    std::string r; for (char c : value) { if (c == '\\' || c == '"') r += '\\'; if (c == '\n') r += "\\n"; else r += c; } return r;
}
static std::string field(const std::string& json, const std::string& key) {
    const std::string marker = "\"" + key + "\":\""; auto begin = json.find(marker); if (begin == std::string::npos) return {};
    begin += marker.size(); std::string r; bool escaped = false;
    for (size_t i = begin; i < json.size(); ++i) { char c = json[i]; if (escaped) { r += c == 'n' ? '\n' : c; escaped = false; } else if (c == '\\') escaped = true; else if (c == '"') break; else r += c; } return r;
}
static bool boolField(const std::string& json, const std::string& key, bool fallback) { const auto p = json.find("\"" + key + "\":"); if (p == std::string::npos) return fallback; return json.compare(p + key.size() + 3, 4, "true") == 0; }
State StateStore::load() {
    State state; const auto current = root_ / "state.json"; const auto backup = root_ / "state.json.bak";
    std::ifstream input(current); if (!input.good()) input.open(backup); if (!input.good()) return state;
    std::string json((std::istreambuf_iterator<char>(input)), {});
    if (json.find("\"schemaVersion\":1") == std::string::npos) return state;
    state.serviceUrl = field(json, "serviceUrl"); state.consolePublicKey = field(json, "consolePublicKey");
    state.sessionToken = field(json, "sessionToken"); state.lastAccountId = field(json, "lastAccountId"); state.lastFolderId = field(json, "lastFolderId"); state.deleteAfterInstall = boolField(json, "deleteAfterInstall", true);
    // Account and catalog records are independently recoverable: older state stays valid if one record is malformed.
    size_t cursor = 0; while ((cursor = json.find("{\"id\":", cursor)) != std::string::npos) { auto end = json.find('}', cursor); if (end == std::string::npos) break; auto row = json.substr(cursor, end - cursor + 1); LibraryItem item; item.id = field(row,"id"); item.accountId = field(row,"accountId"); item.remoteId = field(row,"remoteId"); item.name = field(row,"name"); item.localPath = field(row,"localPath"); item.md5 = field(row,"md5"); item.installedPath = field(row,"installedPath"); item.installedContentId = field(row,"installedContentId"); if (!item.id.empty()) state.library.push_back(item); cursor = end + 1; }
    return state;
}
bool StateStore::save(const State& state, std::string& error) {
    std::error_code ec; fs::create_directories(root_, ec); if (ec) { error = ec.message(); return false; }
    const auto temporary = root_ / "state.json.tmp"; const auto current = root_ / "state.json"; const auto backup = root_ / "state.json.bak";
    std::ofstream output(temporary, std::ios::binary | std::ios::trunc); if (!output) { error = "não foi possível abrir o estado temporário"; return false; }
    output << "{\"schemaVersion\":1,\"serviceUrl\":\"" << escape(state.serviceUrl) << "\",\"consolePublicKey\":\"" << escape(state.consolePublicKey) << "\",\"sessionToken\":\"" << escape(state.sessionToken) << "\",\"lastAccountId\":\"" << escape(state.lastAccountId) << "\",\"lastFolderId\":\"" << escape(state.lastFolderId) << "\",\"deleteAfterInstall\":" << (state.deleteAfterInstall ? "true" : "false") << ",\"library\":[";
    for (size_t i=0; i<state.library.size(); ++i) { const auto& v=state.library[i]; if(i) output << ','; output << "{\"id\":\""<<escape(v.id)<<"\",\"accountId\":\""<<escape(v.accountId)<<"\",\"remoteId\":\""<<escape(v.remoteId)<<"\",\"name\":\""<<escape(v.name)<<"\",\"localPath\":\""<<escape(v.localPath)<<"\",\"md5\":\""<<escape(v.md5)<<"\",\"installedPath\":\""<<escape(v.installedPath)<<"\",\"installedContentId\":\""<<escape(v.installedContentId)<<"\"}"; }
    output << "]}"; output.flush(); output.close();
    if (!output) { error = "falha ao gravar estado"; return false; }
    if (fs::exists(current, ec)) { fs::copy_file(current, backup, fs::copy_options::overwrite_existing, ec); if (ec) { error = ec.message(); return false; } }
    fs::rename(temporary, current, ec); if (ec) { fs::remove(current, ec); ec.clear(); fs::rename(temporary, current, ec); } if (ec) { error = ec.message(); return false; } return true;
}
fs::path StateStore::downloadPath(const Task& task) const { return root_ / "downloads" / task.id / sanitizeFileName(task.displayName); }

#pragma pack(push, 1)
struct Pfs0Header { char magic[4]; uint32_t fileCount, stringTableSize, reserved; };
struct Pfs0RawEntry { uint64_t offset, size; uint32_t stringOffset, reserved; };
#pragma pack(pop)
bool Pfs0::open(const fs::path& path, std::string& error) {
    valid_ = false; entries_.clear(); std::ifstream input(path, std::ios::binary); Pfs0Header header{}; input.read(reinterpret_cast<char*>(&header), sizeof(header));
    if (!input || std::string(header.magic,4) != "PFS0" || header.fileCount == 0 || header.fileCount > 4096 || header.stringTableSize > 4*1024*1024) { error = "NSP inválido: cabeçalho PFS0"; return false; }
    std::vector<Pfs0RawEntry> raw(header.fileCount); input.read(reinterpret_cast<char*>(raw.data()), raw.size()*sizeof(Pfs0RawEntry)); std::string strings(header.stringTableSize, '\0'); input.read(strings.data(), strings.size());
    const uint64_t dataStart = sizeof(header)+raw.size()*sizeof(Pfs0RawEntry)+strings.size(); const uint64_t total = fs::file_size(path);
    for (const auto& entry : raw) { if (entry.stringOffset >= strings.size() || entry.offset > total || entry.size > total-dataStart-entry.offset) { error="NSP inválido: entradas PFS0"; return false; } const char* name=strings.data()+entry.stringOffset; const size_t max=strings.size()-entry.stringOffset; const auto terminator=std::find(name,name+max,'\0'); const size_t length=static_cast<size_t>(terminator-name); if (length==max || length==0) { error="NSP inválido: nome"; return false; } entries_.push_back({std::string(name,length), dataStart+entry.offset, entry.size}); }
    valid_ = true; return true;
}
} // namespace switchdrive
